import * as dotenv from 'dotenv';
dotenv.config();
const {INFLUXDB_URL, INFLUXDB_TOKEN, INFLUXDB_ORG, INFLUXDB_BUCKET, PORT, MQTT_HOST, MQTT_USERNAME, MQTT_PASSWORD} = process.env;
export {INFLUXDB_URL, INFLUXDB_TOKEN, INFLUXDB_ORG, INFLUXDB_BUCKET, PORT, MQTT_HOST, MQTT_USERNAME, MQTT_PASSWORD};